name: Events

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  CompileEventsRepo:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build events directory
      run: ./build-events.sh
    - name: Push code
      uses: actions-x/commit@v6
      with:
        name: arlindohall
        email: hall@hey.com
        branch: main
        files: events EVENTS_VERSION