name: Pandoc

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  CompileHtml:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install pandoc
      run: sudo apt update && sudo apt install -y pandoc
    - name: Compile html
      run: ./compile.sh
    - name: Push code
      uses: actions-x/commit@v2
      with:
        name: arlindohall
        email: hall@hey.com
        branch: main
        files: posts index.html posts.html